
# Resources:
# * https://b-woody.com/posts/2022-05-12-pihole-on-a-rootless-podman-container/
#

apiVersion: v1
kind: Pod
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  containers:
    - name: pihole
      image: 'pihole/pihole:2023.05.2'
      imagePullPolicy: Always
      env:
        - name: TZ
          value: 'US/Mountain'
        - name: WEBPASSWORD
          value: 'DONOTSTOREHERE'
      ports:
        - name: dnstcpport
          containerPort: 53
          hostPort: 1053
          protocol: TCP
        - name: dnsudpport
          containerPort: 53
          hostPort: 1053
          protocol: UDP
        - name: webadminport
          containerPort: 80
          hostPort: 8081
          protocol: TCP
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - name: pihole-dnsmasq-pvc
          mountPath: /etc/dnsmasq.d
        - name: pihole-config-pvc
          mountPath: /etc/pihole
  restartPolicy: Never    # Let systemd handle this.
  volumes:
    - name: pihole-dnsmasq-pvc
      persistentVolumeClaim:
        claimName: pihole-dnsmasq
    - name: pihole-config-pvc
      persistentVolumeClaim:
        claimName: pihole-config