apiVersion: v1
kind: Pod
metadata:
  name: unifi-controller
  labels:
    app: unifi-controller
spec:
  containers:
    - name: unifi-controller
      image: 'lscr.io/linuxserver/unifi-controller:7.4.162'
      imagePullPolicy: Always
      env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'US/Mountain'
      ports:
        - name: webadminport
          containerPort: 8443
          hostPort: 8443
          protocol: TCP
        - name: stunport
          containerPort: 3478
          hostPort: 3478
          protocol: UDP
        - name: apdiscoveryport
          containerPort: 10001
          hostPort: 10001
          protocol: UDP
        - name: devicecommsport
          containerPort: 8080
          hostPort: 8080
          protocol: TCP
        - name: l2discoveryport
          containerPort: 1900
          hostPort: 1900
          protocol: UDP
        - name: guestportalhttpsport
          containerPort: 8843
          hostPort: 8843
          protocol: TCP
        - name: guestportalhttpport
          containerPort: 8880
          hostPort: 8880
          protocol: TCP
        - name: mobilethroughputport
          containerPort: 6789
          hostPort: 6789
          protocol: TCP
        - name: syslogport
          containerPort: 5514
          hostPort: 5514
          protocol: UDP
      securityContext: {}
      volumeMounts:
        - mountPath: /config
          name: unifi-config
  restartPolicy: Never    # Let systemd handle this.
  volumes:
    - name: unifi-config
      hostPath:
        path: /home/poddy/volumes/unifi-config
        type: Directory
